# format:
#
# package
# dependencies
# features
# profiles
# examples

[package]
name = "libquark"
version = "4.0.1"
description = "A lightweight alternative to Electron."
authors = ["Jaydon Nelson <xxdr@duck.com>"]
license = "MIT"
readme = "README_crates.io.md"
repository = "https://codeberg.org/pparaxan/Quark"
edition = "2021"
keywords = [ "web", "gui", "desktop" ]
categories = [ "gui", "web-programming" ]

[dependencies]
libquark-hyaline = "1.0.0"
include_dir = "0.7.4"
tiny_http = "0.12.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true

[[example]]
name = "helloworld"
path = "examples/helloworld.rs"
